name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your branch name if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.12'  # Update Node.js version

    - name: Install pnpm
      run: npm install -g pnpm  # Install pnpm globally

    - name: Install Dependencies
      run: pnpm install  # Install project dependencies

    - name: Build and Export
      run: pnpm run build && pnpm run export

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out